version: '3.9'
services:
    mssqlserverdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "S3nha#2021"
        ports:
            - "1433:1433"
        volumes:
            - C:\dados\volumes\sqlserver:/var/opt/mssql/data
